### PR TITLE
shivani's first commit

### PR DESCRIPTION
**Pull request by kushwahashivani**
bhaiya kaam ho gaya ye feature ka poora

### CODE REVIEW

**Comment by fooliscool** [comment]
ek baar deepak se bhi pooch lo

**Comment by kushwahashivani** [comment]
bhaiya usse pooch ke hi kiya hai

**Comment by fooliscool** [comment]
isme do variable theek karo, vahiyad code hai

**Comment by kushwahashivani** [comment]
bhaiya mera ho gaya, ab sareen dekhegi

**Pull request merged**
